sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qaz135790
  alioss:
    access-key-secret: 6GgUZHebW3Dy49tfGeMVUKgkuf8aJS
    access-key-id: LTAI5tLL1k6BbFidZJPX3opM
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: aivk-sky
  redis:
    host: localhost
    port: 6379
    password: qaz135790
    database: 0
  wechat:
    appid: wxfd520f268379a53d
    secret: 3f8311d4eddb829a53868b59da475eda
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7F40760G
    private-key-file-path: D:\pay\apiclient_key.pem
    api-v3-key: CZBK51236435wxpay435434323FFDuv3
    we-chat-pay-cert-file-path: D:\pay\wechatpay_166D
    notify-url: https://7f6c5c74.r29.cpolar.top/notify/paySuccess
    refund-notify-url: https://7f6c5c74.r29.cpolar.top/notify/refundSuccess
